### PR TITLE
Add Python Package

### LINKED ISSUE #1: Add MQ-Interface Package and Module
Finish generalizing https://github.com/icecube/skymap_scanner/blob/master/skymap_scanner/client/client.py, then get it on PyPI.

### PR DESCRIPTION
**Pull request by ric-evans**
closes #1

### CODE REVIEW

**Comment by ric-evans** [comment]
TODO: update the README

**Comment by dsschult** [comment]
Generally looks good.

1. Is there a basic start script for the pilot?  Or just calling the pilot itself?
2. Can there be an option to write to a raw file instead of pickling?  Just thinking about how to read/write events with simulation.  (this could also be another feature request)

**Comment by ric-evans** [comment]
> 1. Is there a basic start script for the pilot?  Or just calling the pilot itself?
You just call `consume_and_reply()` function. The `main()` from the Skymap scanner had some domain-specific arguments, so I left it out. I could easily add an `if-main` with the basic CLI args, but I'm not sure this would be commonly used. Thoughts?

> 2. Can there be an option to write to a raw file instead of pickling?  Just thinking about how to read/write events with simulation.  (this could also be another feature request)
I could add a "file type" argument: binary, text, pickle, json, ...

**Comment by ric-evans** [comment]
@dsschult re script vs module. Adding a CL arg for `cmd` would match condor/docker patterns. That's good, I guess

**Comment by dsschult** [comment]
> > 1. Is there a basic start script for the pilot?  Or just calling the pilot itself?
> 
> You just call `consume_and_reply()` function. The `main()` from the Skymap scanner had some domain-specific arguments, so I left it out. I could easily add an `if-main` with the basic CLI args, but I'm not sure this would be commonly used. Thoughts?
> 

I guess if we're making this as Python pieces to assemble in a domain-specific way it could be a bit more modular.  Maybe hand the message data off to a custom function (taken as an argument), which by default is the pickler?  And the same for sending new data.

**Comment by ric-evans** [comment]
> > > 1. Is there a basic start script for the pilot?  Or just calling the pilot itself?
> > 
> > 
> > You just call `consume_and_reply()` function. The `main()` from the Skymap scanner had some domain-specific arguments, so I left it out. I could easily add an `if-main` with the basic CLI args, but I'm not sure this would be commonly used. Thoughts?
> 
> I guess if we're making this as Python pieces to assemble in a domain-specific way it could be a bit more modular. Maybe hand the message data off to a custom function (taken as an argument), which by default is the pickler? And the same for sending new data.

That's a good idea. We'd need to require two "function" arguments-- one for the in-message and one for the out-message, otherwise, we'd have to implement logic for detecting the file-open type (ex: "r" vs "rb")

**Comment by ric-evans** [comment]
@dsschult I'll open a new issue with a design for different file encoding options

**Pull request merged**
